package com.wool.hermes.dao.mapper;

import com.wool.hermes.model.database.ConfigDemo;
import com.wool.hermes.model.database.ConfigDemoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConfigDemoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_demo
     *
     * @mbggenerated
     */
    int countByExample(ConfigDemoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_demo
     *
     * @mbggenerated
     */
    int deleteByExample(ConfigDemoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_demo
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_demo
     *
     * @mbggenerated
     */
    int insert(ConfigDemo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_demo
     *
     * @mbggenerated
     */
    int insertSelective(ConfigDemo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_demo
     *
     * @mbggenerated
     */
    List<ConfigDemo> selectByExample(ConfigDemoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_demo
     *
     * @mbggenerated
     */
    ConfigDemo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_demo
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ConfigDemo record, @Param("example") ConfigDemoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_demo
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ConfigDemo record, @Param("example") ConfigDemoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_demo
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ConfigDemo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table config_demo
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ConfigDemo record);

    List<ConfigDemo> selectByExampleWithLimit(ConfigDemoExample example);
}